### ISSUE TITLE
feature: pre-compiled binary wheels for M chip macOS (arm64)

### ISSUE THREAD

**Issue by Co1lin** [tree-sitter/tree-sitter-python#262]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

https://github.com/tree-sitter/py-tree-sitter says "Build from source" will be deprecated and in v0.22.0. However, on arm mac, running `pip install tree-sitter-python` reports "No matching distribution found for tree-sitter-python". I think there is no pre-built wheels for M chip mac.

### Describe the solution you'd like

Release the binary for the M chip mac.

### Describe alternatives you've considered

/

**Comment by kiyoon** [comment]
> ```shell
> pip install git+https://github.com/tree-sitter/tree-sitter-python
> ```

I tried this and still can't install it. How do I resolve this?

```Traceback (most recent call last):
  File "/Users/kiyoon/.config/dotfiles/nvim/find_python_import_in_project.py", line 6, in <module>
    import tree_sitter_python as tspython
  File "/Users/kiyoon/bin/miniforge3/envs/PPMI/lib/python3.11/site-packages/tree_sitter_python/__init__.py", line 3, in <module>
    from ._binding import language
ImportError: dlopen(/Users/kiyoon/bin/miniforge3/envs/PPMI/lib/python3.11/site-packages/tree_sitter_python/_binding.abi3.so, 0x0002): tried: '/Users/kiyoon/bin/miniforge3/envs/PPMI/lib/python3.11/site-packages/tree_sitter_python/_binding.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kiyoon/bin/miniforge3/envs/PPMI/lib/python3.11/site-packages/tree_sitter_python/_binding.abi3.so' (no such file), '/Users/kiyoon/bin/miniforge3/envs/PPMI/lib/python3.11/site-packages/tree_sitter_python/_binding.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

**Comment by tusharsadhwani** [comment]
@kiyoon for intel mac you should be able to `pip install tree-sitter` normally. Does that not work?

**Comment by ObserverOfTime** [comment]
> I tried this and still can't install it. How do I resolve this?

_Something_ is using the wrong architecture. Could be python, pip, conda, or your compiler.

**Comment by kiyoon** [comment]
I think it's my compiler because I had similar problem with rust. But I don't know how to fix it..

**Comment by kiyoon** [comment]
I temporarily forked the repo and modified the CI to publish the wheel files on the Release page. I don't know what's wrong with my compiler, but this worked for me.

https://github.com/kiyoon/tree-sitter-python/releases

**Comment by ObserverOfTime** [comment]
The wheel is included in 0.23.0

**Comment by perseoGI** [comment]
After having successfully installed 0.23.0 in a M chip MacOS, I'm getting this error:

```py
import tree_sitter_python as tspython
from tree_sitter import Language, Parser, Point, Tree

PY_LANGUAGE = Language(tspython.language())
```

Error: 
```
PY_LANGUAGE = Language(tspython.language())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: an integer is required

ERROR: an integer is required
```

Any clue why is this happening?
With a previous installation of this dependency using `git protocol` I didn't get this error:
```
tree-sitter-python @ git+https://github.com/tree-sitter/tree-sitter-python@71778c2a472ed00a64abf4219544edbf8e4b86d7
```

**Comment by ericwb** [comment]
@perseoGI #280 was opened on that issue. For some reason the issue is closed even though it has not been resolved yet.

**Comment by ericwb** [comment]
Unfortunately, no. I'm still waiting for all these bugs to get straightened out.

**Comment by ObserverOfTime** [comment]
You need `tree-sitter==0.23.0`

**Comment by jiezhuzzz** [comment]
@ObserverOfTime The bug persists in version 0.23.
