### ISSUE TITLE
atm language build failed: Python 3.6.5 not supported by gyp

### ISSUE THREAD

**Issue by CooperStansbury** [tree-sitter/tree-sitter-python#31]
Python language build error when running: `apm install python-debugger language-python`. Is tree-sitter incompatible with newer versions of python?

```
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter-python@0.11.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-python@0.11.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter-python package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter-python
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter-python
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/1_/3cmgrq_n4y16hz37wm7mfnkm0000gn/T/apm-install-dir-118512-42406-1tygjwq.yermqp8pvi/npm-debug.log
npm ERR! code 1
```
No `/private/var/folders/1_/3cmgrq_n4y16hz37wm7mfnkm0000gn/T/apm-install-dir-118512-42406-1tygjwq.yermqp8pvi/npm-debug.log` file available. 

Got a more verbose error when attempting to build tree-sitter-cli 'manually' using `npm install tree-sitter-cli`

```
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/anaconda3/bin/python" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:595:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/milk/node_modules/tree-sitter
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by thomasjo** [comment]
@CooperStansbury Yes, sadly it is. Problem stems from the use of `node-gyp`, and the fact GYP only works with Python 2.7. The problem (most likely) never go away since GYP has been replaced by GN in Chromium, which essentially means GYP is abandonware at this point.

**Comment by maxbrunsfeld** [comment]
Yeah, this is a problem for all node modules that contain c or c++ code. Python 2 currently needs to be installed in order to build them. It’s really unfortunate.

**Comment by CooperStansbury** [comment]
Rad, thanks guys!

**Comment by maxbrunsfeld** [comment]
Yes, we can start pre-building the module on all platforms on CI, similar to https://github.com/tree-sitter/tree-sitter-ruby/pull/87 and https://github.com/tree-sitter/tree-sitter-bash/pull/20.

**Comment by banacorn** [comment]
That's great!

**Comment by unphased** [comment]
Is this still the same issue? 

```
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.2.0 | darwin | arm64
npm error gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm error gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm error gyp info spawn args [
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/tree-sitter-python/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/slu/Library/Caches/node-gyp/22.2.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/slu/Library/Caches/node-gyp/22.2.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/slu/Library/Caches/node-gyp/22.2.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/tree-sitter-python',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error In file included from ../bindings/node/binding.cc:3:
npm error ../../nan/nan.h:2548:8: error: no matching member function for call to 'SetAccessor'
npm error   tpl->SetAccessor(
npm error   ~~~~~^~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/22.2.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
npm error   void SetAccessor(
npm error        ^
npm error /Users/slu/Library/Caches/node-gyp/22.2.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
npm error   void SetAccessor(
npm error        ^
npm error In file included from ../bindings/node/binding.cc:3:
npm error ../../nan/nan.h:2594:8: error: no matching member function for call to 'SetAccessor'
npm error   tpl->SetAccessor(
npm error   ~~~~~^~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/22.2.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'PropertyAttribute' for 5th argument
npm error   void SetAccessor(
npm error        ^
npm error /Users/slu/Library/Caches/node-gyp/22.2.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
npm error   void SetAccessor(
npm error        ^
npm error 2 errors generated.
npm error make: *** [Release/obj.target/tree_sitter_python_binding/bindings/node/binding.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
npm error gyp ERR! System Darwin 23.5.0
npm error gyp ERR! command "/opt/homebrew/Cellar/node/22.2.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /Users/slu/entropy-dynamics/nucleus/instrumenter/node_modules/tree-sitter-python
npm error gyp ERR! node -v v22.2.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
```

Are we sure that this tool requires python2 to work? That surely cannot be okay. I don't even know if it is practical to install py2 on macOS anymore. I'm sure it's possible, but...

**Comment by unphased** [comment]
sigh, i seem to be getting (with node 22 now) issues with gyp building for a lot more than just the python tree sitter module.

**Comment by unphased** [comment]
I'm getting similar but different errors with node 23.5.0 now.

**Comment by ObserverOfTime** [comment]
If you're getting "similar but different errors" then it's not the same issue.

**Comment by unphased** [comment]
Sorry, my reporting was sloppy. But the extent of what I can confirm is the following: 

- I have some typescript projects that use tree-sitter bindings for node.
- They don't build properly on node v22, which was the latest version of node when I started the project. 
- Now the same issue plagues node v23. 

Here is a listing of the failure via node v23, it's a very long unsavory GYP build error:

```
npm error code 1
npm error path /Users/slu/instrumenter/node_modules/tree-sitter-python
npm error command failed
npm error command sh -c node-gyp rebuild
npm error CXX(target) Release/obj.target/tree_sitter_python_binding/bindings/node/binding.o
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@23.5.0 | darwin | arm64
npm error gyp info find Python using Python version 3.13.1 found at "/opt/homebrew/opt/python@3.13/bin/python3.13"
npm error gyp info spawn /opt/homebrew/opt/python@3.13/bin/python3.13
npm error gyp info spawn args [
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/slu/instrumenter/node_modules/tree-sitter-python/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/slu/Library/Caches/node-gyp/23.5.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/slu/Library/Caches/node-gyp/23.5.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/slu/Library/Caches/node-gyp/23.5.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/slu/instrumenter/node_modules/tree-sitter-python',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn make
npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm error In file included from ../bindings/node/binding.cc:3:
npm error ../../nan/nan.h:208:12: error: no template named 'CopyablePersistentTraits' in namespace 'v8'; did you mean simply 'CopyablePersistentTraits'?
npm error   208 |     public v8::CopyablePersistentTraits<T> {};
npm error       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error       |            CopyablePersistentTraits
npm error ../../nan/nan.h:207:7: note: 'CopyablePersistentTraits' declared here
npm error   207 | class CopyablePersistentTraits :
npm error       |       ^
npm error ../../nan/nan.h:208:12: error: circular inheritance between 'v8::CopyablePersistentTraits<T>' and 'CopyablePersistentTraits<T>'
npm error   208 |     public v8::CopyablePersistentTraits<T> {};
npm error       |            ^
npm error ../../nan/nan.h:688:39: error: no member named 'IdleNotificationDeadline' in 'v8::Isolate'
npm error   688 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
npm error       |            ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
npm error ../../nan/nan.h:2548:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
npm error  2548 |   tpl->SetAccessor(
npm error       |   ~~~~~^
npm error ../../nan/nan.h:2594:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
npm error  2594 |   tpl->SetAccessor(
npm error       |   ~~~~~^
npm error ../../nan/nan.h:2638:15: error: no member named 'SetAccessor' in 'v8::Object'
npm error  2638 |   return obj->SetAccessor(
npm error       |          ~~~~~^
npm error ../../nan/nan.h:2714:19: error: no matching constructor for initialization of 'v8::NamedPropertyHandlerConfiguration'
npm error  2714 |   tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
npm error       |                   ^
npm error  2715 |       getter_, setter_, query_, deleter_, enumerator_, obj));
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:785:12: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
npm error   785 |   explicit NamedPropertyHandlerConfiguration(
npm error       |            ^
npm error   786 |       NamedPropertyGetterCallback getter,
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:803:3: note: candidate constructor not viable: no known conversion from 'imp::NativePropertyGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'NamedPropertyGetterCallback' (aka 'Intercepted (*)(Local<Name>, const PropertyCallbackInfo<Value> &)') for 1st argument
npm error   803 |   NamedPropertyHandlerConfiguration(
npm error       |   ^
npm error   804 |       NamedPropertyGetterCallback getter,          //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:765:3: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
npm error   765 |   NamedPropertyHandlerConfiguration(
npm error       |   ^
npm error   766 |       NamedPropertyGetterCallback getter,          //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   767 |       NamedPropertySetterCallback setter,          //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   768 |       NamedPropertyQueryCallback query,            //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   769 |       NamedPropertyDeleterCallback deleter,        //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   770 |       NamedPropertyEnumeratorCallback enumerator,  //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   771 |       NamedPropertyDefinerCallback definer,        //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   772 |       NamedPropertyDescriptorCallback descriptor,  //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   773 |       Local<Value> data = Local<Value>(),
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   774 |       PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:754:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
npm error   754 | struct NamedPropertyHandlerConfiguration {
npm error       |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:754:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
npm error   754 | struct NamedPropertyHandlerConfiguration {
npm error       |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error In file included from ../bindings/node/binding.cc:3:
npm error ../../nan/nan.h:2784:19: error: no matching constructor for initialization of 'v8::IndexedPropertyHandlerConfiguration'
npm error  2784 |   tpl->SetHandler(v8::IndexedPropertyHandlerConfiguration(
npm error       |                   ^
npm error  2785 |       getter_, setter_, query_, deleter_, enumerator_, obj));
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:864:12: note: candidate constructor not viable: no known conversion from 'imp::NativeIndexGetter' (aka 'void (*)(unsigned int, const PropertyCallbackInfo<v8::Value> &)') to 'IndexedPropertyGetterCallbackV2' (aka 'v8::Intercepted (*)(unsigned int, const PropertyCallbackInfo<Value> &)') for 1st argument
npm error   864 |   explicit IndexedPropertyHandlerConfiguration(
npm error       |            ^
npm error   865 |       IndexedPropertyGetterCallbackV2 getter = nullptr,
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:882:3: note: candidate constructor not viable: no known conversion from 'imp::NativeIndexGetter' (aka 'void (*)(unsigned int, const PropertyCallbackInfo<v8::Value> &)') to 'IndexedPropertyGetterCallbackV2' (aka 'v8::Intercepted (*)(unsigned int, const PropertyCallbackInfo<Value> &)') for 1st argument
npm error   882 |   IndexedPropertyHandlerConfiguration(
npm error       |   ^
npm error   883 |       IndexedPropertyGetterCallbackV2 getter,
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:844:3: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
npm error   844 |   IndexedPropertyHandlerConfiguration(
npm error       |   ^
npm error   845 |       IndexedPropertyGetterCallbackV2 getter,          //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   846 |       IndexedPropertySetterCallbackV2 setter,          //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   847 |       IndexedPropertyQueryCallbackV2 query,            //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   848 |       IndexedPropertyDeleterCallbackV2 deleter,        //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   849 |       IndexedPropertyEnumeratorCallback enumerator,    //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   850 |       IndexedPropertyDefinerCallbackV2 definer,        //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   851 |       IndexedPropertyDescriptorCallbackV2 descriptor,  //
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   852 |       Local<Value> data = Local<Value>(),
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error   853 |       PropertyHandlerFlags flags = PropertyHandlerFlags::kNone)
npm error       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:833:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
npm error   833 | struct IndexedPropertyHandlerConfiguration {
npm error       |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-template.h:833:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
npm error   833 | struct IndexedPropertyHandlerConfiguration {
npm error       |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error In file included from ../bindings/node/binding.cc:3:
npm error In file included from ../../nan/nan.h:2950:
npm error ../../nan/nan_scriptorigin.h:19:7: error: no matching constructor for initialization of 'v8::ScriptOrigin'
npm error    19 |       v8::ScriptOrigin(v8::Isolate::GetCurrent(), name) {}
npm error       |       ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:64:13: note: candidate constructor not viable: no known conversion from 'Isolate *' to 'Local<Value>' for 1st argument
npm error    64 |   V8_INLINE ScriptOrigin(Local<Value> resource_name,
npm error       |             ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error In file included from ../bindings/node/binding.cc:3:
npm error In file included from ../../nan/nan.h:2950:
npm error ../../nan/nan_scriptorigin.h:23:7: error: no matching constructor for initialization of 'v8::ScriptOrigin'
npm error    23 |       v8::ScriptOrigin(v8::Isolate::GetCurrent()
npm error       |       ^                ~~~~~~~~~~~~~~~~~~~~~~~~~
npm error    24 |                    , name
npm error       |                    ~~~~~~
npm error    25 |                    , To<int32_t>(line).FromMaybe(0)) {}
npm error       |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:64:13: note: candidate constructor not viable: no known conversion from 'Isolate *' to 'Local<Value>' for 1st argument
npm error    64 |   V8_INLINE ScriptOrigin(Local<Value> resource_name,
npm error       |             ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error In file included from ../bindings/node/binding.cc:3:
npm error In file included from ../../nan/nan.h:2950:
npm error ../../nan/nan_scriptorigin.h:30:7: error: no matching constructor for initialization of 'v8::ScriptOrigin'
npm error    30 |       v8::ScriptOrigin(v8::Isolate::GetCurrent()
npm error       |       ^                ~~~~~~~~~~~~~~~~~~~~~~~~~
npm error    31 |                    , name
npm error       |                    ~~~~~~
npm error    32 |                    , To<int32_t>(line).FromMaybe(0)
npm error       |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error    33 |                    , To<int32_t>(column).FromMaybe(0)) {}
npm error       |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:64:13: note: candidate constructor not viable: no known conversion from 'Isolate *' to 'Local<Value>' for 1st argument
npm error    64 |   V8_INLINE ScriptOrigin(Local<Value> resource_name,
npm error       |             ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error /Users/slu/Library/Caches/node-gyp/23.5.0/include/node/v8-message.h:62:17: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 4 were provided
npm error    62 | class V8_EXPORT ScriptOrigin {
npm error       |                 ^~~~~~~~~~~~
npm error 11 errors generated.
npm error make: *** [Release/obj.target/tree_sitter_python_binding/bindings/node/binding.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
npm error gyp ERR! System Darwin 24.2.0
npm error gyp ERR! command "/opt/homebrew/Cellar/node/23.5.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /Users/slu/instrumenter/node_modules/tree-sitter-python
npm error gyp ERR! node -v v23.5.0
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
```

I hope you see why I said that this node 23 failure is "similar but different" to my node 22 failures when it comes to `npm i tree-sitter-python`... 

In terms of where the rubber meets the road on building the software and getting it running, gyp related build failures (which I am told are py2 related but for which I see no evidence for in these gyp build errors) plague all node versions 22 and newer. That is the purpose of my contribution here. 

Due to uncertainty about how long the node treesitter bindings will continue to use GYP, which is dead, and for other reasons, I intend to switch my project to use wasm bindings going forward.
